export type Locale = "en" | "da";

export const copy = {
  en: {
    localeLabel: "EN",
    brand: "NorthSend",
    nav: {
      pricing: "Pricing",
      upload: "Upload",
      login: "Login",
      dashboard: "Dashboard",
      startFree: "Start free",
      logout: "Logout",
    },
    footer: {
      line1: "NorthSend helps businesses send large files in a faster, cleaner, more trustworthy way.",
      line2: "Built for simple sharing today and white-label growth tomorrow.",
    },
    home: {
      badge: "Large file sharing for modern teams",
      title: "Send large files without the usual friction.",
      description:
        "Upload in seconds, share a clean download link, and give clients a smoother experience from the very first file.",
      primaryCta: "Start upload",
      secondaryCta: "Create free account",
      limitsEyebrow: "Simple limits",
      limitsTitle: "Pricing built to convert first and expand account value later.",
      limitsDescription:
        "Start with a free plan that gets people moving fast. Upgrade the businesses that need more storage, longer retention, and better visibility.",
      scrollEyebrow: "Why it converts",
      scrollTitle: "Make the first transfer feel effortless and the paid value obvious.",
      scrollDescription:
        "The homepage leads with action. The sections below do the selling once people already trust the flow.",
      features: [
        {
          title: "Instant first use",
          description: "Visitors understand the product immediately because the first screen is already the product.",
        },
        {
          title: "Natural signup hook",
          description: "Going from 2 GB to 10 GB gives people a real reason to create a free account.",
        },
        {
          title: "Business-ready upgrade",
          description: "White-label pages and bigger limits make the paid plan relevant for real companies.",
        },
      ],
      whiteLabelEyebrow: "White-label",
      whiteLabelTitle: "Turn the same transfer flow into a stronger client-facing experience.",
      whiteLabelDescription:
        "Paying customers can deliver files with more confidence, more control, and a cleaner business presentation.",
      whiteLabelCta: "Preview branding flow",
    },
    plans: {
      guest: { name: "Guest", description: "Files stay online for 24 hours." },
      free: { name: "Free account", description: "Create an account and get 72 hours retention." },
      pro: { name: "Pro", description: "Longer retention and white-label for businesses." },
      pricingEyebrow: "Pricing",
      pricingTitle: "Plans that make the first yes easy and the upgrade obvious.",
      pricingDescription:
        "Use the free plan to win signups. Use Pro Light and Pro to monetize businesses that need more storage, visibility, and control.",
      perTransfer: "Per transfer",
      retention: "Retention",
    },
    uploader: {
      send: "Send",
      uploadZone: "Upload zone",
      title: "Drag files here",
      description: "Upload files in a clean flow that feels easy from the first second.",
      chooseFiles: "Choose files",
      selectedFiles: (count: number) => `${count} file${count === 1 ? "" : "s"} selected`,
      clickToChoose: "Click to choose files",
      dragHint: "Or drag files into this area",
      totalSize: (size: string) => `Total size: ${size}`,
      transferLimit: "Transfer limit",
      retention: "Retention",
      whiteLabel: "White-label",
      included: "Included",
      upgradeRequired: "Upgrade required",
      uploadTransfer: "Upload transfer",
      uploading: "Uploading...",
      uploadProgress: (percent: number) => `${percent}% uploaded`,
      uploadProgressDetail: (uploaded: string, total: string) => `${uploaded} of ${total} transferred`,
      uploadSuccess: "Your transfer is ready. Open the download page and share the link.",
      openDownloadPage: "Open download page",
      moreFiles: (count: number) => `+ ${count} more files`,
      chooseBeforeContinue: "Choose one or more files before continuing.",
      guestsHint: "Guests can send 2 GB. Create a free account to unlock 10 GB and 72 hours retention.",
      uploadMessages: [
        "Checking every file before it goes out.",
        "Keeping the transfer tidy while everything uploads.",
        "Giving this upload a calm, business-like route.",
        "Making sure the handoff looks as smooth as the first click.",
        "Packing things up for a cleaner client delivery.",
      ],
    },
    uploadPage: {
      eyebrow: "Upload",
      title: "Send large files with a clean, professional flow.",
      description:
        "This page uses the same transfer engine as the homepage and applies the right limit for the current plan automatically.",
      createFreeAccount: "Create free account",
      comparePlans: "Compare plans",
    },
    login: {
      eyebrow: "Login",
      title: "Welcome back",
      description: "Log in to manage transfers, view plan details, and unlock billing and branding tools.",
      needAccount: "Need an account?",
      createOne: "Create one here",
      email: "Email",
      password: "Password",
      submit: "Login",
      pending: "Logging in...",
      invalid: "Invalid login details.",
      required: "Email and password are required.",
    },
    signup: {
      eyebrow: "Signup",
      title: "Create your free account",
      description: "Unlock 10 GB transfers, keep files available for 72 hours, and turn first-time visitors into real leads.",
      haveAccount: "Already have an account?",
      login: "Log in",
      name: "Name",
      email: "Email",
      password: "Password",
      submit: "Create account",
      pending: "Creating account...",
      required: "Email and password are required.",
      shortPassword: "Password must be at least 8 characters.",
      exists: "An account with that email already exists.",
    },
    dashboard: {
      eyebrow: "Dashboard",
      title: "Welcome",
      description:
        "Your account is ready. Next, connect real transfers, storage, and billing so this becomes a working customer dashboard.",
      currentAccount: "Current account",
      email: "Email",
      plan: "Plan",
      memberSince: "Member since",
    },
    download: {
      eyebrow: "Download",
      notFoundTitle: "Transfer not found",
      notFoundDescription: "This download link does not exist or has already been removed.",
      expiredTitle: "Transfer expired",
      readyTitle: "Files ready to download",
      expiredDescription: "This transfer has passed its retention window.",
      availableUntil: "Available until",
      downloadFile: "Download file",
    },
  },
  da: {
    localeLabel: "DA",
    brand: "NorthSend",
    nav: {
      pricing: "Priser",
      upload: "Upload",
      login: "Log ind",
      dashboard: "Dashboard",
      startFree: "Start gratis",
      logout: "Log ud",
    },
    footer: {
      line1: "NorthSend hjælper virksomheder med at sende store filer på en hurtigere, renere og mere troværdig måde.",
      line2: "Bygget til enkel deling i dag og white-label vækst i morgen.",
    },
    home: {
      badge: "Store filoverførsler til moderne teams",
      title: "Send store filer uden alt den sædvanlige friktion.",
      description:
        "Upload på få sekunder, del et rent download-link, og giv kunderne en langt bedre oplevelse fra første fil.",
      primaryCta: "Start upload",
      secondaryCta: "Opret gratis konto",
      limitsEyebrow: "Enkle grænser",
      limitsTitle: "Priser bygget til at konvertere hurtigt og øge værdien bagefter.",
      limitsDescription:
        "Start med en gratis plan der får folk hurtigt i gang. Opgrader de virksomheder der har brug for mere storage, længere lagring og mere indsigt.",
      scrollEyebrow: "Hvorfor den konverterer",
      scrollTitle: "Gør første transfer enkel og den betalte værdi tydelig.",
      scrollDescription:
        "Forsiden starter med handling. Sektionerne længere nede gør salgsarbejdet, når brugeren allerede stoler på flowet.",
      features: [
        {
          title: "Brug det med det samme",
          description: "Besøgende forstår produktet med det samme, fordi den første skærm allerede er produktet.",
        },
        {
          title: "Naturlig signup-krog",
          description: "Springet fra 2 GB til 10 GB giver folk en reel grund til at oprette en gratis konto.",
        },
        {
          title: "Klar til virksomheder",
          description: "White-label sider og større limits gør den betalte plan relevant for rigtige virksomheder.",
        },
      ],
      whiteLabelEyebrow: "White-label",
      whiteLabelTitle: "Gør det samme transfer-flow til en stærkere kundeoplevelse.",
      whiteLabelDescription:
        "Betalende kunder kan levere filer med mere tillid, mere kontrol og en langt mere professionel præsentation.",
      whiteLabelCta: "Se branding-flow",
    },
    plans: {
      guest: { name: "Gæst", description: "Filer ligger online i 24 timer." },
      free: { name: "Gratis konto", description: "Opret en konto og få 72 timers opbevaring." },
      pro: { name: "Pro", description: "Længere opbevaring og white-label til virksomheder." },
      pricingEyebrow: "Priser",
      pricingTitle: "Planer der gør det let at sige ja først og opgradere bagefter.",
      pricingDescription:
        "Brug gratis-planen til at få flere oprettelser. Brug Pro Light og Pro til at tjene på virksomheder der har brug for mere storage, mere indsigt og mere kontrol.",
      perTransfer: "Pr. overførsel",
      retention: "Opbevaring",
    },
    uploader: {
      send: "Send",
      uploadZone: "Uploadfelt",
      title: "Træk filer herind",
      description: "Upload filer i et rent flow, der føles nemt fra første sekund.",
      chooseFiles: "Vælg filer",
      selectedFiles: (count: number) => `${count} fil${count === 1 ? "" : "er"} valgt`,
      clickToChoose: "Klik for at vælge filer",
      dragHint: "Eller træk filer ind i dette felt",
      totalSize: (size: string) => `Samlet størrelse: ${size}`,
      transferLimit: "Transfer limit",
      retention: "Opbevaring",
      whiteLabel: "White-label",
      included: "Inkluderet",
      upgradeRequired: "Kræver opgradering",
      uploadTransfer: "Upload filer",
      uploading: "Uploader...",
      uploadProgress: (percent: number) => `${percent}% uploadet`,
      uploadProgressDetail: (uploaded: string, total: string) => `${uploaded} af ${total} overført`,
      uploadSuccess: "Din overførsel er klar. Åbn downloadsiden og del linket.",
      openDownloadPage: "Åbn downloadside",
      moreFiles: (count: number) => `+ ${count} flere filer`,
      chooseBeforeContinue: "Vælg en eller flere filer før du fortsætter.",
      guestsHint: "Gæster kan sende 2 GB. Opret en gratis konto for at få 10 GB og 72 timers opbevaring.",
      uploadMessages: [
        "Vi tjekker lige filerne, mens de bliver sendt afsted.",
        "Vi holder uploaden ren og rolig undervejs.",
        "Vi sender det hele gennem et mere professionelt flow.",
        "Vi gør overleveringen klar, så den føles skarp hos modtageren.",
        "Vi pakker transferen pænt sammen til deling.",
      ],
    },
    uploadPage: {
      eyebrow: "Upload",
      title: "Send store filer i et rent og professionelt flow.",
      description:
        "Denne side bruger den samme transfer-motor som forsiden og bruger automatisk den rigtige grænse for den aktuelle plan.",
      createFreeAccount: "Opret gratis konto",
      comparePlans: "Sammenlign planer",
    },
    login: {
      eyebrow: "Log ind",
      title: "Velkommen tilbage",
      description: "Log ind for at administrere transfers, se din plan og låse op for betaling og branding.",
      needAccount: "Mangler du en konto?",
      createOne: "Opret en her",
      email: "E-mail",
      password: "Adgangskode",
      submit: "Log ind",
      pending: "Logger ind...",
      invalid: "Ugyldige login-oplysninger.",
      required: "E-mail og adgangskode er påkrævet.",
    },
    signup: {
      eyebrow: "Opret konto",
      title: "Opret din gratis konto",
      description: "Få 10 GB transfers, 72 timers opbevaring og gør førstegangsbesøgende til rigtige leads.",
      haveAccount: "Har du allerede en konto?",
      login: "Log ind",
      name: "Navn",
      email: "E-mail",
      password: "Adgangskode",
      submit: "Opret konto",
      pending: "Opretter konto...",
      required: "E-mail og adgangskode er påkrævet.",
      shortPassword: "Adgangskoden skal være mindst 8 tegn.",
      exists: "Der findes allerede en konto med den e-mail.",
    },
    dashboard: {
      eyebrow: "Dashboard",
      title: "Velkommen",
      description:
        "Din konto er klar. Næste skridt er at forbinde rigtige transfers, storage og betaling, så dette bliver et fungerende kundedashboard.",
      currentAccount: "Nuværende konto",
      email: "E-mail",
      plan: "Plan",
      memberSince: "Medlem siden",
    },
    download: {
      eyebrow: "Download",
      notFoundTitle: "Transfer ikke fundet",
      notFoundDescription: "Dette download-link findes ikke eller er allerede blevet fjernet.",
      expiredTitle: "Transfer udløbet",
      readyTitle: "Filer klar til download",
      expiredDescription: "Denne transfer er udløbet.",
      availableUntil: "Tilgængelig indtil",
      downloadFile: "Download fil",
    },
  },
} as const;
