export type Locale = "en" | "da";

export const copy = {
  en: {
    localeLabel: "EN",
    brand: "NorthSend",
    nav: {
      pricing: "Pricing",
      upload: "Upload",
      login: "Login",
      dashboard: "Dashboard",
      startFree: "Start free",
      logout: "Logout",
    },
    footer: {
      line1: "NorthSend helps businesses send large files in a faster, cleaner, more trustworthy way.",
      line2: "Built for simple sharing today and white-label growth tomorrow.",
    },
    home: {
      badge: "Large file sharing for modern teams",
      title: "Stop guessing whether your files are being seen.",
      description:
        "Upload and share your files in seconds, then see exactly who opens and downloads them. Built for people who work with large files every day.",
      primaryCta: "Start upload",
      secondaryCta: "Create free account",
      trust: "Used by creators, agencies, and teams who work with large files",
      limitsEyebrow: "Simple limits",
      limitsTitle: "A setup that grows with you.",
      limitsDescription:
        "Start free and upgrade when you need more control, insight, and better delivery. No hidden complexity. Just a file flow that works.",
      scrollEyebrow: "Why it converts",
      scrollTitle: "Make the first upload simple and the value obvious.",
      scrollDescription:
        "Most services stop at upload. NorthSend helps you understand what happens after the file is sent.",
      features: [
        {
          title: "See what happens next",
          description: "Know when your files are opened and downloaded, without chasing people for updates.",
        },
        {
          title: "Send without waiting",
          description: "Share large files quickly and reliably, even when timing matters.",
        },
        {
          title: "Preview in the browser",
          description: "Let recipients view images and PDFs faster, with less friction in the workflow.",
        },
      ],
      whiteLabelEyebrow: "White-label",
      whiteLabelTitle: "Turn file delivery into a more professional experience.",
      whiteLabelDescription:
        "Deliver files with your own brand, more control, and an experience that matches your business.",
      whiteLabelCta: "See branding options",
      bottomCtaTitle: "Ready to send files the smarter way?",
      bottomCtaDescription: "Upload your first file now and feel the difference immediately.",
      bottomCtaButton: "Upload files",
      fomo: "The first 100 users get intro pricing. When the spots are gone, the price goes up.",
    },
    plans: {
      guest: { name: "Guest", description: "Files stay online for 24 hours." },
      free: { name: "Free account", description: "Create an account and get 72 hours retention." },
      pro: { name: "Pro", description: "Longer retention and white-label for businesses." },
      pricingEyebrow: "Pricing",
      pricingTitle: "Plans that make the first yes easy and the upgrade obvious.",
      pricingDescription:
        "Use the free plan to win signups. Use Pro Light and Pro to monetize businesses that need more storage, visibility, and control.",
      perTransfer: "Per transfer",
      retention: "Retention",
    },
    uploader: {
      send: "Send",
      uploadZone: "Upload zone",
      title: "Drop your files in. We handle the rest.",
      description: "Upload quickly and securely, share the link, and keep full visibility on what happens next.",
      chooseFiles: "Choose files",
      selectedFiles: (count: number) => `${count} file${count === 1 ? "" : "s"} selected`,
      clickToChoose: "Click to choose files",
      dragHint: "Or drag files into this area",
      totalSize: (size: string) => `Total size: ${size}`,
      transferLimit: "Transfer limit",
      retention: "Retention",
      whiteLabel: "White-label",
      included: "Included",
      upgradeRequired: "Upgrade required",
      uploadTransfer: "Upload transfer",
      uploading: "Uploading...",
      uploadProgress: (percent: number) => `${percent}% uploaded`,
      uploadProgressDetail: (uploaded: string, total: string) => `${uploaded} of ${total} transferred`,
      uploadSuccess: "Your transfer is ready. Open the download page and share the link.",
      openDownloadPage: "Open download page",
      moreFiles: (count: number) => `+ ${count} more files`,
      chooseBeforeContinue: "Choose one or more files before continuing.",
      guestsHint: "Create a free account to send up to 15 GB per file and keep transfers available for 3 days.",
      uploadMessages: [
        "Checking every file before it goes out.",
        "Keeping the transfer tidy while everything uploads.",
        "Giving this upload a calm, business-like route.",
        "Making sure the handoff looks as smooth as the first click.",
        "Packing things up for a cleaner client delivery.",
      ],
    },
    uploadPage: {
      eyebrow: "Upload",
      title: "Send large files with a clean, professional flow.",
      description:
        "This page uses the same transfer engine as the homepage and applies the right limit for the current plan automatically.",
      createFreeAccount: "Create free account",
      comparePlans: "Compare plans",
    },
    login: {
      eyebrow: "Login",
      title: "Welcome back",
      description: "Log in to manage transfers, view plan details, and unlock billing and branding tools.",
      needAccount: "Need an account?",
      createOne: "Create one here",
      email: "Email",
      password: "Password",
      submit: "Login",
      pending: "Logging in...",
      invalid: "Invalid login details.",
      required: "Email and password are required.",
    },
    signup: {
      eyebrow: "Signup",
      title: "Create your free account",
      description: "Unlock 10 GB transfers, keep files available for 72 hours, and turn first-time visitors into real leads.",
      haveAccount: "Already have an account?",
      login: "Log in",
      name: "Name",
      email: "Email",
      password: "Password",
      submit: "Create account",
      pending: "Creating account...",
      required: "Email and password are required.",
      shortPassword: "Password must be at least 8 characters.",
      exists: "An account with that email already exists.",
    },
    dashboard: {
      eyebrow: "Dashboard",
      title: "Welcome",
      description:
        "Your account is ready. Next, connect real transfers, storage, and billing so this becomes a working customer dashboard.",
      currentAccount: "Current account",
      email: "Email",
      plan: "Plan",
      memberSince: "Member since",
    },
    download: {
      eyebrow: "Download",
      notFoundTitle: "Transfer not found",
      notFoundDescription: "This download link does not exist or has already been removed.",
      expiredTitle: "Transfer expired",
      readyTitle: "Files ready to download",
      expiredDescription: "This transfer has passed its retention window.",
      availableUntil: "Available until",
      downloadFile: "Download file",
    },
  },
  da: {
    localeLabel: "DA",
    brand: "NorthSend",
    nav: {
      pricing: "Priser",
      upload: "Upload",
      login: "Log ind",
      dashboard: "Dashboard",
      startFree: "Start gratis",
      logout: "Log ud",
    },
    footer: {
      line1: "NorthSend hjælper virksomheder med at sende store filer på en hurtigere, renere og mere troværdig måde.",
      line2: "Bygget til enkel deling i dag og white-label vækst i morgen.",
    },
    home: {
      badge: "Store filoverførsler til moderne teams",
      title: "Stop med at gætte om dine filer bliver set",
      description:
        "Upload og del dine filer på få sekunder, og se præcis hvem der åbner og downloader dem. Bygget til dig der arbejder med store filer hver dag.",
      primaryCta: "Start upload",
      secondaryCta: "Opret gratis konto",
      trust: "Brugt af creators, bureauer og teams der arbejder med store filer",
      limitsEyebrow: "Enkle grænser",
      limitsTitle: "En løsning der vokser med dig",
      limitsDescription:
        "Start gratis og opgrader når du har brug for mere kontrol, indsigt og bedre levering. Ingen skjulte begrænsninger. Kun en løsning der virker.",
      scrollEyebrow: "Hvorfor den konverterer",
      scrollTitle: "Send filer og få kontrol bagefter",
      scrollDescription:
        "De fleste tjenester stopper ved upload. Vi viser dig hvad der sker bagefter.",
      features: [
        {
          title: "Se præcis hvad der sker",
          description: "Få besked når dine filer bliver åbnet og downloadet. Du behøver aldrig følge op igen.",
        },
        {
          title: "Send uden ventetid",
          description: "Upload og del store filer hurtigt og stabilt, selv når det virkelig gælder.",
        },
        {
          title: "Preview direkte i browseren",
          description: "Modtagere kan se filer uden at downloade først. Hurtigere workflow og færre friktioner.",
        },
      ],
      whiteLabelEyebrow: "White-label",
      whiteLabelTitle: "Gør dine filoverførsler til en professionel oplevelse",
      whiteLabelDescription:
        "Lever filer med dit eget brand, mere kontrol og en oplevelse der matcher din virksomhed.",
      whiteLabelCta: "Se branding muligheder",
      bottomCtaTitle: "Klar til at sende dine filer smartere?",
      bottomCtaDescription: "Upload din første fil nu og oplev forskellen med det samme.",
      bottomCtaButton: "Upload filer",
      fomo: "De første 100 brugere får adgang til intropris. Når pladserne er væk, stiger prisen.",
    },
    plans: {
      guest: { name: "Gæst", description: "Filer ligger online i 24 timer." },
      free: { name: "Gratis konto", description: "Opret en konto og få 72 timers opbevaring." },
      pro: { name: "Pro", description: "Længere opbevaring og white-label til virksomheder." },
      pricingEyebrow: "Priser",
      pricingTitle: "Planer der gør det let at sige ja først og opgradere bagefter.",
      pricingDescription:
        "Brug gratis-planen til at få flere oprettelser. Brug Pro Light og Pro til at tjene på virksomheder der har brug for mere storage, mere indsigt og mere kontrol.",
      perTransfer: "Pr. overførsel",
      retention: "Opbevaring",
    },
    uploader: {
      send: "Send",
      uploadZone: "Uploadfelt",
      title: "Træk dine filer ind – vi klarer resten",
      description: "Upload dine filer hurtigt og sikkert. Del linket og få fuldt overblik over hvad der sker bagefter.",
      chooseFiles: "Vælg filer",
      selectedFiles: (count: number) => `${count} fil${count === 1 ? "" : "er"} valgt`,
      clickToChoose: "Klik for at vælge filer",
      dragHint: "Eller træk filer ind i dette felt",
      totalSize: (size: string) => `Samlet størrelse: ${size}`,
      transferLimit: "Transfer limit",
      retention: "Opbevaring",
      whiteLabel: "White-label",
      included: "Inkluderet",
      upgradeRequired: "Kræver opgradering",
      uploadTransfer: "Upload filer",
      uploading: "Uploader...",
      uploadProgress: (percent: number) => `${percent}% uploadet`,
      uploadProgressDetail: (uploaded: string, total: string) => `${uploaded} af ${total} overført`,
      uploadSuccess: "Din overførsel er klar. Åbn downloadsiden og del linket.",
      openDownloadPage: "Åbn downloadside",
      moreFiles: (count: number) => `+ ${count} flere filer`,
      chooseBeforeContinue: "Vælg en eller flere filer før du fortsætter.",
      guestsHint: "Opret en gratis konto og send op til 15 GB pr. fil med 3 dages lagring.",
      uploadMessages: [
        "Vi tjekker lige filerne, mens de bliver sendt afsted.",
        "Vi holder uploaden ren og rolig undervejs.",
        "Vi sender det hele gennem et mere professionelt flow.",
        "Vi gør overleveringen klar, så den føles skarp hos modtageren.",
        "Vi pakker transferen pænt sammen til deling.",
      ],
    },
    uploadPage: {
      eyebrow: "Upload",
      title: "Send store filer i et rent og professionelt flow.",
      description:
        "Denne side bruger den samme transfer-motor som forsiden og bruger automatisk den rigtige grænse for den aktuelle plan.",
      createFreeAccount: "Opret gratis konto",
      comparePlans: "Sammenlign planer",
    },
    login: {
      eyebrow: "Log ind",
      title: "Velkommen tilbage",
      description: "Log ind for at administrere transfers, se din plan og låse op for betaling og branding.",
      needAccount: "Mangler du en konto?",
      createOne: "Opret en her",
      email: "E-mail",
      password: "Adgangskode",
      submit: "Log ind",
      pending: "Logger ind...",
      invalid: "Ugyldige login-oplysninger.",
      required: "E-mail og adgangskode er påkrævet.",
    },
    signup: {
      eyebrow: "Opret konto",
      title: "Opret din gratis konto",
      description: "Få 10 GB transfers, 72 timers opbevaring og gør førstegangsbesøgende til rigtige leads.",
      haveAccount: "Har du allerede en konto?",
      login: "Log ind",
      name: "Navn",
      email: "E-mail",
      password: "Adgangskode",
      submit: "Opret konto",
      pending: "Opretter konto...",
      required: "E-mail og adgangskode er påkrævet.",
      shortPassword: "Adgangskoden skal være mindst 8 tegn.",
      exists: "Der findes allerede en konto med den e-mail.",
    },
    dashboard: {
      eyebrow: "Dashboard",
      title: "Velkommen",
      description:
        "Din konto er klar. Næste skridt er at forbinde rigtige transfers, storage og betaling, så dette bliver et fungerende kundedashboard.",
      currentAccount: "Nuværende konto",
      email: "E-mail",
      plan: "Plan",
      memberSince: "Medlem siden",
    },
    download: {
      eyebrow: "Download",
      notFoundTitle: "Transfer ikke fundet",
      notFoundDescription: "Dette download-link findes ikke eller er allerede blevet fjernet.",
      expiredTitle: "Transfer udløbet",
      readyTitle: "Filer klar til download",
      expiredDescription: "Denne transfer er udløbet.",
      availableUntil: "Tilgængelig indtil",
      downloadFile: "Download fil",
    },
  },
} as const;
